### ISSUE TITLE
Paid membership changes to Free when paid members registered for free content

### ISSUE THREAD

**Issue by braddalton** [restrictcontentpro/restrict-content#45]
A member has a premium ( paid ) membership which is still active but they also signed up for free content while logged in using the same username. When they did this, their membership changed from premium to free and they could no longer access premium content.

**Comment by pippinsplugins** [comment]
Hi @braddalton!

This Github repo is for the lite version of Restrict Content and not the Pro version. Since you're issue is related to the Pro version, can you please send us over a support ticket? https://restrictcontentpro.com/support

In your ticket, please include as much relevant information as possible, including screenshots of your membership settings and the customer account so we can best determine what happened and why.

Thanks!
