### ISSUE TITLE
Add promo section to admin screen

### ISSUE THREAD

**Issue by SeanChDavis** [restrictcontentpro/restrict-content#48]
At this point, only the single settings page would make sense. So I'm going to add a sidebar area (most likely) there.

**Comment by SeanChDavis** [comment]
Alright, @nosegraze! This is ready for your test/review. The PR description explains everything I've done.

**Comment by ashleyfae** [comment]
Excellent job @SDavisMedia !

I did notice one minor styling issue on the CTA button while using the Vendd theme. Here's a screenshot, but it's kind of subtle so might help if you install Vendd to test:

![2019-11-06 15_23_05](https://user-images.githubusercontent.com/6324272/68311420-6d36c380-00a9-11ea-87e7-4281a78acf32.png)

There's a _green_ border around the CTA button. This is because of the class name `cta-button`. Vendd uses that as well and some of the styles are overlapping. We could fix this by prefixing the RCP CTA button class with `rc-`

**Comment by SeanChDavis** [comment]
@nosegraze Good catch!!! I'll get that fixed up.

**Comment by SeanChDavis** [comment]
@nosegraze I went ahead and prefixed all of the classes, since they're all pretty general. That should do the trick.

**Comment by ashleyfae** [comment]
@SDavisMedia That's perfect - thanks!

Left one more comment here: https://github.com/restrictcontentpro/restrict-content/pull/49/files#r343175166
